const app=document.querySelector('#app');
const modal=document.querySelector('#modal');
const modalContent=document.querySelector('#modalContent');
let currentRole='customer';
let currentSection='overview';
const providers=[
{name:'PixelForge Studio',initials:'PF',cat:'Web Development',rating:'4.9',price:'From $650',tags:['Web apps','Marketplaces','UI/UX']},
{name:'BrightHome Experts',initials:'BH',cat:'Home Services',rating:'4.8',price:'From $120',tags:['Renovation','Electrical','Plumbing']},
{name:'GrowthLine Agency',initials:'GL',cat:'Marketing',rating:'5.0',price:'From $450',tags:['SEO','Paid ads','Strategy']},
{name:'Northstar Design',initials:'ND',cat:'Design',rating:'4.9',price:'From $300',tags:['Branding','Product design','3D']},
{name:'CodeCraft Labs',initials:'CC',cat:'Web Development',rating:'4.7',price:'From $900',tags:['React','Node.js','Dashboards']},
{name:'SocialSpark',initials:'SS',cat:'Marketing',rating:'4.8',price:'From $250',tags:['Content','Social media','Email']}
];
const navs={customer:['Overview','My requests','Offers','Messages','Bookings','Payments','Profile'],provider:['Overview','Find leads','My offers','Messages','Bookings','Earnings','Services'],admin:['Overview','Users','Listings','Categories','Bookings','Payments','Messages','Modules','Settings']};
function clone(id){return document.querySelector(id).content.cloneNode(true)}
function bind(root=document){root.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{if(b.dataset.role)currentRole=b.dataset.role;render(b.dataset.view)});root.querySelectorAll('[data-action="login"]').forEach(b=>b.onclick=()=>openLogin());root.querySelectorAll('[data-action="close-modal"]').forEach(b=>b.onclick=closeModal)}
function render(view='home'){app.innerHTML='';app.appendChild(clone(`#${view}Tpl`));bind(app);if(view==='marketplace')renderProviders();if(view==='dashboard')renderDashboard();window.scrollTo({top:0,behavior:'smooth'})}
function renderProviders(filter=''){const grid=document.querySelector('#providerGrid');if(!grid)return;const cat=document.querySelector('#categoryFilter')?.value||'All categories';const list=providers.filter(p=>(cat==='All categories'||p.cat===cat)&&(`${p.name} ${p.cat} ${p.tags.join(' ')}`.toLowerCase().includes(filter.toLowerCase())));grid.innerHTML=list.map((p,i)=>`<article class="provider-card"><div class="provider-top"><span class="provider-avatar">${p.initials}</span><div><h3>${p.name}</h3><small>${p.cat} · ★ ${p.rating}</small></div></div><p>Verified professional with fast response time and marketplace experience.</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><b>${p.price}</b><div class="card-actions"><button class="primary" onclick="openProvider(${i})">View profile</button><button class="secondary" onclick="openMessage('${p.name}')">Message</button></div></article>`).join('');document.querySelector('#resultCount').textContent=`${list.length} results`;document.querySelector('#categoryFilter').onchange=()=>renderProviders(document.querySelector('#marketSearch').value);document.querySelector('[data-action="search-market"]').onclick=()=>renderProviders(document.querySelector('#marketSearch').value);document.querySelector('[data-action="clear-filters"]').onclick=()=>{document.querySelector('#categoryFilter').value='All categories';document.querySelector('#marketSearch').value='';renderProviders()}}
function renderDashboard(){document.querySelectorAll('[data-switch-role]').forEach(b=>{b.classList.toggle('active',b.dataset.switchRole===currentRole);b.onclick=()=>{currentRole=b.dataset.switchRole;currentSection='overview';renderDashboard()}});document.querySelector('#roleLabel').textContent=`${currentRole[0].toUpperCase()+currentRole.slice(1)} workspace`;const side=document.querySelector('#sideNav');side.innerHTML=navs[currentRole].map(x=>`<button class="${x.toLowerCase()===currentSection?'active':''}" data-sec="${x.toLowerCase()}">${x}</button>`).join('');side.querySelectorAll('button').forEach(b=>b.onclick=()=>{currentSection=b.dataset.sec;renderDashboard()});renderDashContent()}
function renderDashContent(){const title=document.querySelector('#dashTitle'),c=document.querySelector('#dashContent');const section=currentSection;title.textContent=section[0].toUpperCase()+section.slice(1);if(currentRole==='admin'&&section==='modules'){c.innerHTML=`<div class="dash-card"><h2>Module manager</h2><p>Enable, disable or replace marketplace modules without changing the full system.</p><div class="module-manager">${['User accounts','Provider profiles','Booking system','WhatsApp integration','Email notifications','Online payments','Reviews & ratings','Dispute management'].map((m,i)=>`<div class="module-row" draggable="true"><span>☰</span><span><b>${m}</b><small style="display:block;color:var(--muted)">Module ${i+1}</small></span><div class="toggle ${i<6?'on':''}"></div></div>`).join('')}</div></div>`;c.querySelectorAll('.toggle').forEach(t=>t.onclick=()=>t.classList.toggle('on'));return}
const roleData={customer:{stats:[['Active requests','4'],['New offers','9'],['Upcoming bookings','2'],['Messages','6']],rows:[['Website redesign','Web Development','3 offers','Open'],['Apartment painting','Home Services','5 offers','Reviewing'],['Logo design','Design','1 offer','Booked']]},provider:{stats:[['New leads','18'],['Offers sent','12'],['Bookings','7'],['This month','$4,820']],rows:[['Marketplace MVP','Web Development','$1,000–2,500','New'],['Landing page','Web Development','$500–900','Responded'],['Admin dashboard','Web Development','$1,500+','Interview']]},admin:{stats:[['Total users','3,248'],['Providers','864'],['Active bookings','176'],['Revenue','$28,940']],rows:[['New provider review','User verification','Today','Pending'],['Payment dispute #284','Support','2h ago','Open'],['Category request','Marketplace','Yesterday','Review']]}}[currentRole];
c.innerHTML=`<div class="stats">${roleData.stats.map(s=>`<div class="stat-card"><small>${s[0]}</small><b>${s[1]}</b></div>`).join('')}</div><div class="dash-grid"><div class="dash-card"><div style="display:flex;justify-content:space-between;align-items:center"><h2>${currentRole==='admin'?'Recent activity':'Recent items'}</h2><button class="primary" onclick="openCreate('${currentRole}')">+ New</button></div><table class="table"><thead><tr><th>Title</th><th>Category</th><th>Value</th><th>Status</th></tr></thead><tbody>${roleData.rows.map(r=>`<tr>${r.map((x,i)=>`<td>${i===3?`<span class="status">${x}</span>`:x}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="dash-card"><h2>Communication</h2><p style="color:var(--muted)">Contact users directly through integrated channels.</p><a class="primary full" style="display:block;text-align:center;text-decoration:none;margin:12px 0" target="_blank" href="https://wa.me/15551234567">Open WhatsApp</a><a class="secondary full" style="display:block;text-align:center;text-decoration:none" href="mailto:hello@marketflow.demo">Send email</a></div></div>`}
function openProvider(i){const p=providers[i];modalContent.innerHTML=`<span class="eyebrow">VERIFIED PROVIDER</span><h2>${p.name}</h2><p>${p.cat} · ★ ${p.rating}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><p>Experienced specialist available for new projects. Typical response time: under 2 hours.</p><button class="primary full" onclick="openMessage('${p.name}')">Request a quote</button>`;modal.classList.remove('hidden')}
function openMessage(name){modalContent.innerHTML=`<h2>Message ${name}</h2><div class="form-grid"><input placeholder="Your name"><input placeholder="Email address"><textarea rows="5" placeholder="Describe your project"></textarea><button class="primary" onclick="success('Message sent successfully')">Send message</button><a class="secondary" style="text-align:center;text-decoration:none" target="_blank" href="https://wa.me/15551234567">Continue on WhatsApp</a></div>`;modal.classList.remove('hidden')}
function openCreate(role){modalContent.innerHTML=`<h2>${role==='customer'?'Post a new request':role==='provider'?'Create an offer':'Create admin item'}</h2><div class="form-grid"><input placeholder="Title"><select><option>Select category</option><option>Web Development</option><option>Design</option><option>Marketing</option></select><textarea rows="5" placeholder="Details"></textarea><input placeholder="Budget"><button class="primary" onclick="success('Created successfully')">Create</button></div>`;modal.classList.remove('hidden')}
function openLogin(){modalContent.innerHTML=`<h2>Welcome back</h2><p style="color:var(--muted)">Choose a demo account to enter the platform.</p><div class="form-grid"><input placeholder="Email"><input type="password" placeholder="Password"><button class="primary" onclick="closeModal();render('dashboard')">Log in</button></div>`;modal.classList.remove('hidden')}
function success(msg){modalContent.innerHTML=`<div style="text-align:center;padding:20px"><div style="font-size:46px">✓</div><h2>${msg}</h2><p style="color:var(--muted)">This demo interaction is complete.</p><button class="primary" onclick="closeModal()">Done</button></div>`}
function closeModal(){modal.classList.add('hidden')}
modal.onclick=e=>{if(e.target===modal)closeModal()}
document.querySelector('#themeToggle').onclick=()=>{const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'light':'dark';localStorage.setItem('theme',dark?'light':'dark');document.querySelector('#themeToggle').textContent=dark?'☾':'☀'};document.documentElement.dataset.theme=localStorage.getItem('theme')||'light';document.querySelector('#themeToggle').textContent=document.documentElement.dataset.theme==='dark'?'☀':'☾';bind(document);render('home');
